### ISSUE TITLE
SNN nodes were not the same as the Neumann algorithm for redundancy 2. m_val = 1 graph_size = 3. radiation =0.0. 

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/snncompare#119]
A snn graph did not yield the same results as the original snn:
```py
121/600 [runs]
{'adaptation': {'redundancy': 2},
 'algorithm': {'MDSA': {'m_val': 1}},
 'export_images': False,
 'export_types': None,
 'graph_nr': 0,
 'graph_size': 3,
 'iteration': 0,
 'max_duration': None,
 'overwrite_sim_results': False,
 'overwrite_snn_creation': None,
 'overwrite_snn_propagation': None,
 'overwrite_visualisation': False,
 'radiation': {'neuron_death': 0.0},
 'seed': 7,
 'show_snns': False,
 'simulator': 'nx',
 'unique_id': '15e6db337956028adbad1a95150fd336410481b15d14129a79907a34f56a28fe'}

start stage I:   0.49973 [s]
Start stage II   {'adaptation': {'redundancy': 2},
 'algorithm': {'MDSA': {'m_val': 1}},
 'export_images': False,
 'export_types': None,
 'graph_nr': 0,
 'graph_size': 3,
 'iteration': 0,
 'max_duration': None,
 'overwrite_sim_results': False,
 'overwrite_snn_creation': None,
 'overwrite_snn_propagation': None,
 'overwrite_visualisation': False,
 'radiation': {'neuron_death': 0.0},
 'seed': 7,
 'show_snns': False,
 'simulator': 'nx',
 'unique_id': '15e6db337956028adbad1a95150fd336410481b15d14129a79907a34f56a28fe'}
3.70091 [s]
Start stage III  0.00013 [s]
Traceback (most recent call last):
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/name/git/snn/snncompare/src/snncompare/__main__.py", line 34, in <module>
    process_args(args, custom_config_path)
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/arg_parser/process_args.py", line 56, in process_args
    Experiment_runner(exp_setts)
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 112, in __init__
    self.__perform_run(self.experiment_config, self.run_configs)
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 164, in __perform_run
    ).timeit(1)
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 340, in __perform_run_stage_4
    if set_results(
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/process_results/process_results.py", line 39, in set_results
    return perform_mdsa_results_computation_if_needed(
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/process_results/process_results.py", line 70, in perform_mdsa_results_computation_if_needed
    set_mdsa_snn_results(m_val, run_config, stage_2_graphs)
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snnalgorithms/src/snnalgorithms/sparse/MDSA/apply_results_to_graphs.py", line 65, in set_mdsa_snn_results
    assert_valid_results(
  File "/home/name/anaconda/envs/snncompare/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/name/git/snn/snnalgorithms/src/snnalgorithms/sparse/MDSA/apply_results_to_graphs.py", line 130, in assert_valid_results
    raise ValueError(
ValueError: SNN count per node for: snn_algo_graph, are not equal to  the default/Neumann node counts:
SNN nodes:    {'counter_0': 0, 'counter_1': 0, 'counter_2': 0, 'passed': False}
!=
Neumann nodes:{'counter_0': 1, 'counter_1': 2, 'counter_2': 0}
Node:counter_0 has different counts.

```

https://github.com/a-t-0/snncompare/commit/f14b3576746544e0631d22934f7741e3bdd526ff

**Comment by a-t-0** [comment]
Based on 
```sh
python -m src.snncompare -e mdsa_size3_m2_adap_rad -x png -ov
```
Expectation is that the runtime is computed incorrectly for with adaptation. The images were cut off after 9 steps, even though with m_val it needs more. So take m_val into account when running simulation, then try again.

**Comment by a-t-0** [comment]
Alternatively, with reverse on:
```sh
python -m src.snncompare -e mdsa_long_no_overwrite -r 207 -j1 -j2 -j4 -rev -x svg -
```
yielding run config (207/600): 
```py
{'adaptation': {'redundancy': 6},
 'algorithm': {'MDSA': {'m_val': 1}},
 'graph_nr': 2,
 'graph_size': 5,
 'max_duration': None,
 'radiation': {'neuron_death': 0.0},
 'seed': 7,
 'simulator': 'nx',
 'unique_id': '34f06c5f1e42fe9e595531bc2e524bfb59fb8c3ee787375c6e847a34a798a561'}
```
Also has error.

- [ ] Determine why `selector m=0 (and m=1), node_index = 3` connects to: `degree receivers node-circuit=2,3,5, m_val=0 (and m=1)` (and all degree receivers of that respective circuit).

**Comment by a-t-0** [comment]
For latter (207/600) the degree receivers did not inhibit each other. so at `t=19`, `degree_receiver_2_0_0` did not inhibit `degree_receiver_2_1_0` directly. This allowed the latter to still spike in `t=20` which caused an erroneous count.

**Comment by a-t-0** [comment]
in `run_on_networkx.py`:
```py
# if t <45:
        # if t in [38, 39, 40,41]:
        if t in [28,29,30,31]:
            print(
                f't={t}, {len(snn_graph.nodes["degree_receiver_3_2_1"]["nx_lif"])}'
            )
            print(
                f't={t}, len={len(snn_graph.nodes["degree_receiver_4_2_1"]["nx_lif"])}'
            )
            print_neuron_properties(
                neurons=[
                    snn_graph.nodes["degree_receiver_3_2_1"]["nx_lif"][t],
                    snn_graph.nodes["degree_receiver_4_2_1"]["nx_lif"][t],
                    snn_graph.nodes["selector_4_1"]["nx_lif"][t],
                    snn_graph.nodes["counter_2"]["nx_lif"][t],
                ],
                static=True,
                ids=["deg_3_2_1", "deg_4_2_1","sel_4_1", "counter_2"],
                spikes=[
                    snn_graph.nodes["degree_receiver_3_2_1"]["nx_lif"][
                        t
                    ].spikes,
                    snn_graph.nodes["degree_receiver_4_2_1"]["nx_lif"][
                        t
                    ].spikes,
                    snn_graph.nodes["selector_4_1"]["nx_lif"][
                        t
                    ].spikes,
                    snn_graph.nodes["counter_2"]["nx_lif"][
                        t
                    ].spikes,
                ],
            )

```
