### ISSUE TITLE
assert stage1 is completed.

### ISSUE THREAD

**Issue by a-t-0** [a-t-0/snncompare#178]
debug5. Possibly related to always create new data in 3 (`or True`) checks. First fix random numbers on isomorphic graph.

260/41472 [runs]
{'adaptation': {'redundancy': 2},
 'algorithm': {'MDSA': {'m_val': 0}},
 'graph_nr': 0,
 'graph_size': 5,
 'max_duration': None,
 'radiation': {'neuron_death': 0.01},
 'seed': 9,
 'simulator': 'simsnn',
 'unique_id': '9630ba742e5ce2d0b1993c692f4dc0bbf0b3229a500ae248e99b9b9666364625'}
Execution speed of snncompare.Experiment_runner.Experiment_runner.perform_run_stage_1:
Found:1 unique input graphs.
run_config.isomorphic_hash_input=646c4ffdec7c3b688313fcfec6df6ea9
Found:1 unique input graphs.
run_config.isomorphic_hash_input=646c4ffdec7c3b688313fcfec6df6ea9
{0: 2, 1: 3, 2: 2, 3: 2, 4: 3}
Found:1 unique input graphs.
run_config.isomorphic_hash_input=646c4ffdec7c3b688313fcfec6df6ea9
Traceback (most recent call last):
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/name/git/snn/snncompare/src/snncompare/__main__.py", line 24, in <module>
    process_args(args=args, custom_config_path=custom_config_path)
  File "/home/name/git/snn/snncompare/src/snncompare/arg_parser/process_args.py", line 56, in process_args
    Experiment_runner(
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 129, in __init__
    self.__perform_run(
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 165, in __perform_run
    results_nx_graphs = self.perform_run_stage_1(
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/name/miniconda/envs/snncompare/lib/python3.10/site-packages/customshowme/core.py", line 57, in time
    _r = f(*args, **kwargs)
  File "/home/name/git/snn/snncompare/src/snncompare/Experiment_runner.py", line 268, in perform_run_stage_1
    assert_has_outputted_stage_1(run_config=run_config)
  File "/home/name/git/snn/snncompare/src/snncompare/import_results/load_stage_1_and_2.py", line 155, in assert_has_outputted_stage_1
    raise ValueError("Error, stage 1 was not completed.")
ValueError: Error, stage 1 was not completed.
(snncompare) name@name:~/git/snn/snncompare$

**Comment by a-t-0** [comment]
Resolved by removing or True.
